-- Add new audit actions for screen time types and allowances
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCREENTIME_TYPE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCREENTIME_TYPE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCREENTIME_TYPE_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCREENTIME_TYPE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCREENTIME_ALLOWANCE_UPDATED';
